spellchecker: hunspell

matrix:
- name: python
  sources:
  - fipy/terms/**/*
  dictionary:
    wordlists:
    - .en-custom.txt
  pipeline:
  - pyspelling.filters.python:
      comments: false
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore multiline content between fences (fences can have 3 or more back ticks)
      # ```
      # content
      # ```
      - open: '(?s)^(?P<open> *`{3,})$'
        close: '^(?P=open)$'
      # Ignore text between inline back ticks
      - open: '(- )?(?P<open>`+)'
        close: '(?P=open)'
      # Ignore doctest blocks
      #  Source consists of a PS1 line followed by zero or more PS2 lines.
      #  Want consists of any non-blank lines that do not start with PS1.
      #  Adapted from doctest.py: DocTestParser._EXAMPLE_RE
      - open: '(?P<source>(?:^(?P<indent>[ ]*)>>> .*)(?:\n(?=P<indent>)\.\.\. .*)*)\n?'
        content: ''
        close: '(?P<want>(?:(?![ ]*$)(?![ ]*>>> ).*$\n?)*)'
      # Ignore reStructuredText roles
      - open: ':(?:(attr|func|meth|math|mod)):`'
        close: '`'
      # Ignore reStructuredText literals
      - open: '::$'
        close: '(?P<literal>(?:((?P<indent>[ ]+).*$)|(\n))+)'
