channels:
  - conda-forge
dependencies:
  # setuptools 72.x breaks `test` and `test_suite`.
  # [72.1.0](https://setuptools.pypa.io/en/stable/history.html#v72-1-0)
  # restores `test`, but `test_suite`still doesn't work right.
  - setuptools <= 72.0
  - python=2.7
  - numpy
  - scipy
  - matplotlib-base
  - future
  - packaging
  - pip
  - mpich
  - mpi4py
  # petsc 3.20.2_*_102 is broken on macOS,
  # as a result of linking scotch 7.0.2
  # https://github.com/conda-forge/petsc-feedstock/issues/180
  - scotch <7
  - petsc4py
platforms:
  - linux-64
  - osx-64
  - osx-arm64
