# Conda package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda

jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        conda.packages: '"traitsui<7.0.0" "gmsh<4.0"'
      Python39:
        python.version: '3.9'
        conda.packages: 'gmsh'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment --channel conda-forge mamba
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      mamba install --quiet --yes --channel conda-forge --only-deps python=$(python.version) fipy
      mamba install --quiet --yes --channel conda-forge $(conda.packages)      
    displayName: Install Anaconda packages

  - bash: |
      source activate myEnvironment
      pip install scikit-fmm
    displayName: Install pip packages

  - bash: |
      source activate myEnvironment
      python setup.py egg_info
      python setup.py test --deprecation-errors
    displayName: test
