# Conda package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda

variables:
  system.debug: true
  system.log: true

jobs:
  - job: Test
    strategy:
      matrix:
        linux-py27-pysparse:
          image: ubuntu-latest
          python.version: 2.7
          conda.packages: '"traitsui<7.0.0" "gmsh<4.0"'
          FIPY_SOLVERS: pysparse
          MPIRUN:
        linux-py39-petsc:
          image: ubuntu-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: petsc
          MPIRUN:
        linux-py39-petsc-parallel:
          image: ubuntu-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: petsc
          MPIRUN: 'mpirun -np 2'
        linux-py39-scipy:
          image: ubuntu-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: scipy
          MPIRUN:
        linux-py39-trilinos:
          image: ubuntu-latest
          python.version: 3.9
          conda.packages: 'gmsh pytrilinos'
          FIPY_SOLVERS: trilinos
          MPIRUN:
        macos-py27-pysparse:
          image: macos-latest
          python.version: 2.7
          conda.packages: '"traitsui<7.0.0" "gmsh<4.0"'
          FIPY_SOLVERS: pysparse
          MPIRUN:
        macos-py39-petsc:
          image: macos-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: petsc
          MPIRUN:
        macos-py39-petsc-parallel:
          image: macos-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: petsc
          MPIRUN: 'mpirun -np 2'
        macos-py39-scipy:
          image: macos-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: scipy
          MPIRUN:
        macos-py39-trilinos:
          image: macos-latest
          python.version: 3.9
          conda.packages: 'gmsh pytrilinos'
          FIPY_SOLVERS: trilinos
          MPIRUN:
        windows-py39-scipy:
          image: windows-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: scipy
          MPIRUN:

    pool:
      vmImage: $(image)

    steps:
    - template: templates/install.yml
      parameters:
        python.version: $(python.version)
        conda.packages: $(conda.packages)

    - bash: |
        conda env export
      displayName: Environment

    - bash: |
        source activate myEnvironment
        python setup.py install
        $MPIRUN python setup.py test --deprecation-errors
      env:
        FIPY_SOLVERS: $(FIPY_SOLVERS)
        MPIRUN: $(MPIRUN)
      displayName: Test

  - job: Docs
    pool:
      vmImage: $(image)

    steps:
    - template: templates/install.yml
      parameters:
        python.version: 3.9
        conda.packages:

    - bash: |
        export ETS_TOOLKIT=null
        python setup.py build_docs --html
        tar -czf html.tar.gz -C documentation/_build html
      displayName: HTML
