# Conda package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda

jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        conda.packages: '"traitsui<7.0.0" "gmsh<4.0"'
      Python39:
        python.version: '3.9'
        conda.packages: 'gmsh'

  steps:
  - template: templates/install_linux.yml
    parameters:
      python.version: $(python.version)
      conda.packages: $(conda.packages)

  - bash: |
      source activate myEnvironment
      python setup.py egg_info
      python setup.py test --deprecation-errors
    displayName: test
