# Conda package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda

variables:
  system.debug: true
  system.log: true

jobs:
  - job: Test
    strategy:
      matrix:
        linux-py27-pysparse:
          image: ubuntu-latest
          python.version: 2.7
          conda.packages: '"traitsui<7.0.0" "gmsh<4.0"'
          FIPY_SOLVERS: pysparse
        linux-py39-petsc:
          image: ubuntu-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: petsc
        linux-py39-scipy:
          image: ubuntu-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: scipy
        linux-py39-trilinos:
          image: ubuntu-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: trilinos
        macos-py27-pysparse:
          image: macos-latest
          python.version: 2.7
          conda.packages: '"traitsui<7.0.0" "gmsh<4.0"'
          FIPY_SOLVERS: pysparse
        macos-py39-petsc:
          image: macos-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: petsc
        macos-py39-scipy:
          image: macos-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: scipy
        macos-py39-trilinos:
          image: macos-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: trilinos
        windows-py39-scipy:
          image: windows-latest
          python.version: 3.9
          conda.packages: gmsh
          FIPY_SOLVERS: scipy

    pool:
      vmImage: $(image)

    steps:
    - template: templates/install.yml
      parameters:
        python.version: $(python.version)
        conda.packages: $(conda.packages)

    - bash: |
        source activate myEnvironment
        python setup.py install
        python setup.py test --deprecation-errors
      env:
        FIPY_SOLVERS: $(FIPY_SOLVERS)
      displayName: Test
