name: fipy
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib-base
  - future
  - packaging
  - mpich
  - mpi4py
  - petsc4py
  - mayavi
  - gmsh <4.0|>=4.5.2
  - sphinx
  - pandas
  - pip
  - sphinxcontrib-bibtex
  - numpydoc
  - pip:
    - -e ..
