name: fipy
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.6
  - future
  - numpy
  - scipy
  - gmsh
  - mpi4py
  - petsc4py
  - matplotlib
  - mayavi
  - pip:
    - "--editable=../"
