name: fipy
channels:
  - conda-forge
  - defaults
dependencies:
  - python =2.7
  - numpy
  - scipy
  - gmsh <4.0
  - pysparse
  - pytrilinos
  - mpi4py
  - matplotlib
  - mayavi
  - weave
  - pip:
    - "--editable=../"
