name: fipy
channels:
  - guyer
  - conda-forge
  - defaults
dependencies:
  - python =2.7
  - numpy
  - scipy
  - gmsh
  - pysparse
  - mpi4py
  - matplotlib
  - mayavi
  - fipytrilinos
  - pip:
    - "--editable=./"
